### ISSUE TITLE
Catastrophic failure when using as npm script

### ISSUE THREAD

**Issue by passcod** [phpfmt/php.tools#100]
In my projects, I use npm to organise scripts. For this tool, my `"scripts"` section looks like this:

```json
"scripts": {
  ...
  "prephpfmt": "npm run composer-install",
  "phpfmt": "hhvm vendor/phpfmt/fmt/fmt.phar --config=.php.tools.ini .",
  ...
}
```

This is invoked using:

```
npm run phpfmt
```

But running this results in _all touched files to be **replaced by this**_:

```

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, ping, prefix, prune, publish, r, rb, rebuild, remove,
    repo, restart, rm, root, run-script, s, se, search, set,
    show, shrinkwrap, star, stars, start, stop, t, tag, team,
    test, tst, un, uninstall, unlink, unpublish, unstar, up,
    update, upgrade, v, verison, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /home/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.3.12 /home/.nvm/versions/node/v5.0.0/lib/node_modules/npm
```

Presumably, this tool attempts to rerun itself in such a way that it reuses the `npm...` command, modifies it in such a way that it removes or replaces the `run` command with something else, and then proceeds to overwrite all concerned files with the output, to catastrophic result.

Fortunately, that's what git is for.

But still, this is a particularly frustrating failure mode, especially when all other tools act correctly.

**Comment by passcod** [comment]
I tried modifying the script line with:

```
"phpfmt": "bash -c 'hhvm vendor/phpfmt/fmt/fmt.phar --config=.php.tools.ini .'",
```

to better simulate running in a shell. It still fails, this time replacing the files with:

```

Warning: No such file or directory in phar:///app/vendor/phpfmt/fmt/fmt-external.phar/fmt-external.stub.php on line 3373
```

Extracting the PHAR gives this:

```php
	$getoptLongOptions = ['help', 'pass::'];
	if ($inPhar) {
		$getoptLongOptions[] = 'version';
	}
	$opts = getopt('h', $getoptLongOptions);

	if (isset($opts['version'])) {
		if ($inPhar) {
			echo $argv[0], ' ', VERSION, PHP_EOL;
		}
		exit(0);
	}

	if (!isset($opts['pass'])) {
		fwrite(STDERR, 'pass is not declared. cannot run.');
		exit(1);
	}

	$pass = sprintf('%s.php', basename($opts['pass']));
	if (!file_get_contents($pass)) { // <== Line 3373
		fwrite(STDERR, sprintf('pass file "%s" is not found. cannot run.', $pass));
		exit(1);
	}
	include $pass;

	if (isset($opts['h']) || isset($opts['help'])) {
		showHelp($argv, $enableCache, $inPhar);
		exit(0);
	}

	$fmt = new CodeFormatter(basename($opts['pass']));
	echo $fmt->formatCode(file_get_contents('php://stdin'));
	exit(0);
```

**Comment by passcod** [comment]
I've noticed that the output also gives me the following Notices:

```
Notice: Undefined index: -1 in phar:///app/vendor/phpfmt/fmt/fmt.phar/fmt.stub.php on line 1973 
```

Extracting the phar again:

```php
protected function leftToken($ignoreList = []) {
		$i = $this->leftTokenIdx($ignoreList);

		return $this->tkns[$i]; // <== Line 1973
	}

	protected function leftTokenIdx($ignoreList = []) {
		$ignoreList = $this->resolveIgnoreList($ignoreList);

		$i = $this->walkLeft($this->tkns, $this->ptr, $ignoreList);

		return $i;
	}
```

What??

**Comment by ccirello** [comment]
1 - HHVM is not supported. As you can see at https://github.com/phpfmt/php.tools#requirements

2 - Make sure you are not calling external passes in your configuration file. Typos are often the cause of such accidental calls.

**Comment by passcod** [comment]
It's a bit dishonest to point to a requirement you added _for_ this issue. But ok, no HHVM. Thanks :)

**Comment by passcod** [comment]
Also, further investigation is needed, but if configuration file typos can cause such drastic loss of data, I'd very much consider that a bug.

**Comment by ccirello** [comment]
Actually HHVM support has been dropped a while ago. All you need is to look for the commit in the logs. My mistake was to think people would ignore HHVM if I had removed it from Readme. Well you are the one to prove me wrong. 

Having said that, running the application in HHVM results in unspecified behavior, i.e. alla bets are off and anything can happen. Including catastrophic failures. 

Switch to php 5.6 with xdebug disabled and the performance will be almost on par with HHVM. 

If such failures happen after the switch, then I will consider this a bug.

**Comment by ccirello** [comment]
Regarding the dishonesty part. Keep communication civil.

**Comment by passcod** [comment]
This _was_ civil. Had you said "HHVM is not supported, see here, and I've now added an explicit mention in the Readme", that would have been completely honest. As you said it, I interpreted it as "Look, it says so on the readme"... which would have been perfectly fine if you hadn't _just_ changed it to say that. In fact, other people have read this conversation (out-of-band) and have interpreted it in _exactly the same way_. I understand that's not what you meant. When I made the comment, I specifically included the "a bit" qualifier because I considered this a minor wording issue and wanted to point it out.

**Comment by ccirello** [comment]
HHVM was not mentioned in README.md, so there is no reason to infer that it was supported.

I don't grade dishonesty. It might be a black or white view of the world, but I strongly try to side myself with honesty. 

Calling people names, in this case dishonest, is an act of offense and keeping arguing about it has just shut this conversation down.
