### ISSUE TITLE
require_once parentheses parsing issue

### ISSUE THREAD

**Issue by matchdav** [phpfmt/php.tools#49]
just want to point out that
```require_once(dirname(__FILE__) . '/bootstrap.php');```
maps to
```require_once dirname(__FILE__ . '/bootstrap.php');```

what the hell

**Comment by phpfmt** [comment]
@matchdav I am sorry for this inconvenience. You might want to exclude the `RemoveIncludeParentheses` pass.

If you are using sublime-phpfmt, just add to your configuration file:
```
{
...
"excludes": ["RemoveIncludeParentheses"]
...
}
```

**Comment by phpfmt** [comment]
@matchdav Please, consider upgrading php.tools and sublime-phpfmt.
