### ISSUE TITLE
stripping out wrong closing parens

### ISSUE THREAD

**Issue by xcsrz** [phpfmt/php.tools#50]
An update from a couple days ago broke the parentheses removal from require/include/etc.  It should be removing the first opening (which it does) and the last closing.  But it's taking the first closing and breaking files syntax.

http://tinypic.com/r/2ni9lkn/8

**Comment by phpfmt** [comment]
@xcsrz I am sorry for this bug. I am going to fix it ASAP.

**Comment by phpfmt** [comment]
@xcsrz Please, upgrade to https://github.com/phpfmt/php.tools/releases/tag/10.2.1
