### ISSUE TITLE
autocompletion tool?

### ISSUE THREAD

**Issue by Dgame** [phpfmt/php.tools#54]
Would it be possible to build an open source auto-completion tool for php?

**Comment by dericofilho** [comment]
There is such thing already being used in sublime-phpfmt. 

dericofilho/php.oracle generates a sqlite database with the code information to provide autocompletion. Take a look at https://github.com/phpfmt/sublime-phpfmt/blob/4f2a9a6d90fdf9a37f8fa1d45e1663ede20626cc/phpfmt.py#L1060

**Comment by Dgame** [comment]
Ah, nice. Is it possible to call it from the outside? Then I could integrate it in Atom. :)

**Comment by Dgame** [comment]
Ah, I see. Your autocomplete tool parse _every_ identifier, without considering the scope.

Consider this example:
```php
<?php

class Bar {
    public function fooquatz() {

    }
}

class Foo {
    public function foobar() {
        
    }
}

$f = new Foo();
$f->foo
```
I get suggestion for `foorbar` as well as `fooquatz`. But only `foobar` is valid.

Is that intended?

**Comment by dericofilho** [comment]
> Ah, nice. Is it possible to call it from the outside? Then I could integrate it in Atom. :)

It uses STs internal autocomplete service to display the autocomplete results. But the autocomplete content itself is returned by `oracle.php`

> Is that intended?
That is not intended, but it was good enough for my own needs. Ideally it should be able to track variable types and offer a restricted set of options. But the further you go into call chains, much more complex it becomes to keep track of proper type. In the end, you might find yourself developing a VM of PHP just to be able to query a variable type. Also, keep in mind that often it is not possible to extract variable type from static analysis. In your case, if `$f` is passed into `function fnc($f)`, within `fnc` you would have no hints of which type `$f` is.

**Comment by Dgame** [comment]
That is true (until you use TypeHints). But for the basics it would be _very_ helpful.

**Comment by dericofilho** [comment]
@Dgame patches are welcome at https://github.com/phpfmt/php.oracle :smile:

**Comment by Dgame** [comment]
Seems that your Parser thinks that both Methods belongs to class Foo.

**Comment by dericofilho** [comment]
Could you please file a bug with an example at phpfmt/php.oracle please?

**Comment by Dgame** [comment]
Of course.
