### ISSUE TITLE
OrganizeClass adds new line after last method

### ISSUE THREAD

**Issue by rjp2525** [phpfmt/php.tools#56]
The `OrganizeClass` pass always adds an additional line (see tests [364](https://github.com/phpfmt/php.tools/blob/master/src/tests/364-organize-class.out#L69), [369](https://github.com/phpfmt/php.tools/blob/master/src/tests/369-organize-class.out#L17) and [370](https://github.com/phpfmt/php.tools/blob/master/src/tests/370-organize-class.out#L8)) between the last method and the closing brace for the class. This is an issue when following the [PSR-2 standard](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#41-extends-and-implements).

**Comment by ccirello** [comment]
@rjp2525 please, upgrade to https://github.com/phpfmt/php.tools/releases/tag/13.0.2
