### ISSUE TITLE
Groupped use declaration issue

### ISSUE THREAD

**Issue by iotch** [phpfmt/php.tools#57]
Hello. It seems like the tool is removing dependencies that actually used.
This code:

````php
use Acme\Vendor\{
    A,
    B
};
use Acme\Vendor\C;

class Test {
    
    public function __construct()
    {
        $c = new C;
        $c = B::staticMethod();        
    }
    
}
````

being converted to this:

````php
use Acme\Vendor\C;;

class Test {

	public function __construct() {
		$c = new C;
		$c = B::staticMethod();
	}

}
````
Is there any way to disable `use` cleanup in the SublimeText3 plugin config?
Thanks.

**Comment by ccirello** [comment]
I am sorry for this bug.  I am going to fix it ASAP. Consider disabling OrderUseClause pass.

**Comment by iotch** [comment]
Thank you, Carlos!

**Comment by ccirello** [comment]
Please upgrade to https://github.com/phpfmt/php.tools/releases/tag/13.0.5 and https://github.com/phpfmt/sublime-phpfmt/releases/tag/7.8.0

**Comment by iotch** [comment]
Sorry for the late reply, but it still removes any grouped namespaces:

````php
use A\B\C\{
    D,
    E,
    F
};
````

becomes 

````php
use A\B\C\F;
````

I did a fresh install of version 9.4.0 but the issue is still there. Do I need to tweak default settings somehow? 
Thanks.

**Comment by ccirello** [comment]
Open a new issue. Also, make sure a longer use case is provided. One that shows all imports are used.
