### ISSUE TITLE
An issue when adding “ReindentSwitchBlocks” to phpfmt settings

### ISSUE THREAD

**Issue by w12100931** [phpfmt/php.tools#58]
I faced an issue that after adding the "ReindentSwitchBlocks" additional transformation to my settings and formatted my project by it, some long strings in switch section would automatically indent once, especially query strings. And everytime I did that, it would indent again.

It might be caused by my inappropriate coding style, but I'm trying to figure out what's going on.

Thank you.

Here's my settings:

{
"enable_auto_align": true,
"format_on_save": true,
"indent_with_space": 4,
"passes":
[
    "AlignEquals",
    "AlignDoubleArrow",
    "AlignDoubleSlashComments",
    "AlignGroupDoubleArrow",
    "LongArray",
    "OrderMethod",
    "ReindentAndAlignObjOps",
    "ReindentSwitchBlocks",
],
"php_bin": "C:\\Sublime Text 3\\x64\\Data\\Packages\\php56\\php.exe",
"psr2": true,
"version": 3
}

And here are some sample codes facing the issue:

switch($a) {
  case 'a':
    $query = " select a from b
               inner join c on b.id = c.id";
  break;
}

**Comment by ccirello** [comment]
I am sorry for this bug. I am going to fix it as soon as possible.

**Comment by w12100931** [comment]
thank you for your rapid reply :)

**Comment by ccirello** [comment]
Please upgrade to https://github.com/phpfmt/php.tools/releases/tag/13.0.6 and https://github.com/phpfmt/sublime-phpfmt/releases/tag/7.9.0
