### ISSUE TITLE
Problem with 'PrettyPrintDocBlocks'

### ISSUE THREAD

**Issue by sjdaws** [phpfmt/php.tools#60]
We have a kind of weird situation where our class docblocks contain HTML which is then rendered by a third party program. They look something like this:
```php
<?php

/**
 * This is a test
 *
 * <dl>
 * <dt>$apage</dt>
 * <dd>
 *     The page object. (mandatory)
 *     The page content can be retrieved using <tt>$apage->getContent()</tt>.
 * </dd>
 * </dl>
 *
 * @subpackage Portal\Modules\Page\Functions\Block
 *
 * @author Name
 *
 * @see Page
 *
 * @param  array  $args The block function parameters in array format
 * @return string The rendered html content
 */
```

If we have PrettyPrintDocBlocks on every time we save there are 2 additional asterisks added between the lines containing `</dl>` and `@subpackage` so they end up like this:
```php
 * </dl>
 *
 *
 *
 * @subpackage Portal\Modules\Page\Functions\Block
```

The number of asterisks seem directly related to how many other phpDoc variables we have, for example if we remove the `@param` and `@array` lines only 1 asterisk is added.

Do you know why this is happening?

**Comment by ccirello** [comment]
@sjdaws it seems a bug. I am going to fix it ASAP.

**Comment by sjdaws** [comment]
I appreciate it, thank you very much.

**Comment by ccirello** [comment]
@sjdaws Please, upgrade to https://github.com/phpfmt/php.tools/releases/tag/13.1.0

**Comment by sjdaws** [comment]
Confirm fixed, thanks again. Is there somewhere I can donate to php.tools development?

**Comment by ccirello** [comment]
I appreciate that. Unfortunately I am not a non-profit company, therefore I cannot accept donations and any money I receive I must pay taxes, which usually is more troublesome than the donated values. 

If you ever need me for hired freelance jobs for phpfmt, either me or one of the contributors could be available. Personally I still cannot issue VAT receipts.
