### ISSUE TITLE
Newline before return

### ISSUE THREAD

**Issue by abhimanyusharma003** [phpfmt/php.tools#62]
I think there is missing formatter that will add new line before return statements. As of Symphony standards.

```
Add a blank line before return statements, unless the return is alone inside a statement-group (like an if statement);
```
http://symfony.com/doc/current/contributing/code/standards.html

```
<?php

class SomeClass
{
    public function methodFirst($value)
    {
        $value = 'something';
        return $value;
    }
}
```

To

```
<?php

class SomeClass
{
    public function methodFirst($value)
    {
        $value = 'something';

        return $value;
    }
}
```

**Comment by ccirello** [comment]
Can you produce a PR with this feature?

**Comment by ccirello** [comment]
I will reopen this issue if someone volunteers for doing this.

**Comment by abhimanyusharma003** [comment]
I will give a try, but not sure if it will work out as expected.

**Comment by ccirello** [comment]
I am going to provide any support you might need.
