### ISSUE TITLE
No spaces for array operators

### ISSUE THREAD

**Issue by cariboufute** [phpfmt/php.tools#63]
When using math operators with arrays, there is no spaces around operators unlike when used with numbers.

Before formatting and wished:
```
 $params = $givenParams + [$parentParam => $parentIds];
```

After actual formatting:
```
$params = $givenParams+[$parentParam => $parentIds];
```

**Comment by ccirello** [comment]
Upgrade to https://github.com/phpfmt/php.tools/releases/tag/13.5.0

**Comment by cariboufute** [comment]
Wow fast! Thanks a lot! Will this be also upgraded in the Sublime Text 3 package?

**Comment by ccirello** [comment]
Yes. On ST2/3 upgrade to https://github.com/phpfmt/sublime-phpfmt/releases/tag/7.14.0

**Comment by cariboufute** [comment]
Great, thanks!
