### ISSUE TITLE
Version is greater, but error still shows. 

### ISSUE THREAD

**Issue by jgacuca567** [phpfmt/php.tools#64]
I am using the MAMP stack on Mac. Current Version of PHP is 5.6.7 

PHP Current Version Installed on CLI is PHP 5.6.11, I Keep getting the error, 

PHP 5.6 or newer is required.
Please, upgrade your local PHP installation

I would like to know what I am missing or doing wrong. Thanks

**Comment by ccirello** [comment]
Ensure that you have the right PHP version declared on your $PATH/%PATH%.

If you are using ST plugin, ensure that you are putting whole path in `php_bin` key in the configuration file.

**Comment by jgacuca567** [comment]
@ccirello  Quick questions, How would I find my Path and how can I find my php_bin in the ST Plugin?

**Comment by ccirello** [comment]
ST offers the option to open the file in the plugin menu

**Comment by jgacuca567** [comment]
@ccirello Thanks, I am now able to use PHPFormat. Works Excellent.
