### ISSUE TITLE
Ignores PHP version?

### ISSUE THREAD

**Issue by sodacrackers** [phpfmt/php.tools#67]
Running a current PHP version but pfpfmt format now says PHP 5.6 or greater is needed. Any possibilities? 

```
$php --version
PHP 5.6.13 (cli) (built: Sep  9 2015 10:21:48) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

$whereis php
/usr/bin/php
```

**Comment by ccirello** [comment]
Paste here the output of `phpfmt: troubleshoot information`

**Comment by morvanabonin** [comment]
This problems happens to me too.
![phpfmt-bug](https://cloud.githubusercontent.com/assets/1622341/10176305/476b5ca6-66ca-11e5-8f05-7047141cdfb7.png)

**Comment by ccirello** [comment]
@morvanabonin paste here the output of phpfmt: troubleshoot information

**Comment by ccirello** [comment]
ping @morvanabonin @sodacrackers

**Comment by morvanabonin** [comment]
Hello @ccirello, there are two configs, default and user, when I set in config user, fixed the problem.

Sorry for bothering you.
