### ISSUE TITLE
Getting "Cannot run program" error in PHPStorm 9

### ISSUE THREAD

**Issue by tlshaheen** [phpfmt/php.tools#75]
Using PHPStorm v9.0.2, PHP v5.6.10, and phpfmt v15.1.1.

When I attempt to run phpfmt on a file via PHPStorm, I get this: `Error running phpfmt: Cannot run program "php ~/.composer/vendor/bin/fmt.php" (in directory "/mypath/phpstorm-project-settings/myproject"): error=2, No such file or directory`

I can run `php ~/.composer/vendor/bin/fmt.php` just fine via the command line. 

What am I missing with the config? I've tried "which php" and setting the explicit path in PHPStorm to `php` and to `fmt.php`, and that did not fix it.

<img width="681" alt="screen shot 2015-10-12 at 2 22 04 pm" src="https://cloud.githubusercontent.com/assets/385724/10435253/c9e69ad4-70ec-11e5-832f-ea783a28bc8a.png">

**Comment by ccirello** [comment]
Replace the tilde mark with the complete directory address and try again, please.

**Comment by tlshaheen** [comment]
Same issue - I've tried writing the full path to my `php` as well.

`Error running phpfmt: Cannot run program "php /Users/lukeshaheen/.composer/vendor/bin/fmt.php" (in directory "/Users/lukeshaheen/Documents/All Sites/phpstorm-project-settings/TestProject"): error=2, No such file or directory`

**Comment by ccirello** [comment]
@tlshaheen OK! Please:
In program: `/Applications/MAMP/bin/php/php5.6.10/bin/php` 
In parameters: `/Users/lukeshaheen/.composer/vendor/bin/fmt.php "$FileDir$/$FileName$"`

**Comment by ccirello** [comment]
Please, open a PR with a screenshot similar to what is now.
