### ISSUE TITLE
Output file (-o=file.php) and missing file

### ISSUE THREAD

**Issue by iEFdev** [phpfmt/php.tools#78]
I installed fmt (globally) with composer, and then tested it on a file (from its folder)...

    [… fmttest]$ fmt.phar --psr2 MyFile.php

It worked great :+1: But there was no backup~ made, so I tried another one with `-o=…` added

    [… fmttest]$ fmt.phar -o=MyFile.fmt.php --psr2 MyFile.php

Which gave me the error:

    File not found: $HOME/.composer/vendor/phpfmt/fmt/MyFile.php
     ::  code: 255

Not in my folder?

_Or perhaps one can't run it that way?_

**Comment by ccirello** [comment]
It seems a bug. I am going to fix it in the next release.

**Comment by ccirello** [comment]
> But there was no backup~ made

For single files, that's the expected behavior. Backup files are meant to be protection against massive data change, especially for those files not under revision control.

> so I tried another one with -o=… added
Bug fixed in the upcoming release (check 01dbc4a9fd6c89eb30b462d06e5096792a11c437)

**Comment by iEFdev** [comment]
Thanks. That was fast. :+1:  Ok, so no backups for single files.

- - -

Another small thing I noticed this morning. When it made separate lines from a oneliner…

    protected $data, $default = null;

    protected $data;
    $default = null;

_Or should I make a separate issue, if you prefer that._

**Comment by ccirello** [comment]
Open a separate issue
