### ISSUE TITLE
Recursively formatting directory sets file mode permission to 0 when using backup (the default)

### ISSUE THREAD

**Issue by mfn** [phpfmt/php.tools#80]
My first time experience was that, running this tool within vagrant on a shared folder on my sources make a files essentially chmod 0, i.e. no flag was so on the modified files and thus couldn't be read anymore.

My local dirty hack was to comment out all lines containing `$oldchmod = fileperms($file);` or `chmod($file, $oldchmod);`.

Found no command line switch to disable this behaviour, sure would appreciate it.

**Comment by Shaked** [comment]
Hey @mfn , I am very sorry for this bug. Would you mind sharing your VagrantFile here? It might help me to reproduce this bug faster.

**Comment by ccirello** [comment]
This (unexpected) behavior was introduced by me. I believe the best approach is to create a switch that disables it.

**Comment by mfn** [comment]
I think I found the bug: does not seem to be related to vagrant, but that's the only environment where I had a recent PHP version. And it's only exhibited when working on directories recursively:

If you look at https://github.com/phpfmt/php.tools/blob/bbec0967c223099035b611ac763b39d2dd14238c/src/cli-core.php#L466-L470 and https://github.com/phpfmt/php.tools/blob/bbec0967c223099035b611ac763b39d2dd14238c/src/cli-core.php#L518-L522 you see this fragment:
```PHP
file_put_contents($file . '-tmp', $fmtCode);
$backup && rename($file, $file . '~');
$oldchmod = fileperms($file);
rename($file . '-tmp', $file);
chmod($file, $oldchmod);
```
By default, `$backup` is true. What happens is that the file gets moved and *then* the permission are tried to be read: returns `false` and gets applied as `chmod($file, 0)`, thus removing all permissions of the new files.

Turning of backup with `--no-backup` "fixed" it too for me.

Sorry for the confusion about the vagrant thing and not producing a better report in the first place, it was already too late ...

**Comment by ccirello** [comment]
Applied suggested fix manually.
