### ISSUE TITLE
Double-double colon on next line does not get indented

### ISSUE THREAD

**Issue by mfn** [phpfmt/php.tools#81]
Example code:
```PHP
<?php
Foobar
    ::bar()
    ->baz;
```
turns into
```PHP
<?php
Foobar
::bar()
    ->baz;
```
I would have expected the code not to change.

PhpStorm does format it like the first sample.

**Comment by Shaked** [comment]
I am very sorry for this bug. I will take a close look ASAP. 

@ccirello this might be directly related to https://github.com/phpfmt/vim-phpfmt/issues/12, what do you think?

**Comment by ccirello** [comment]
Not really. It should follow the rules of `ReindentAndAlignObjOps` and `ReindentObjOps`.

**Comment by Shaked** [comment]
@mfn - would you mind posting the passes & configuration that you are using?

**Comment by ccirello** [comment]
In the next release, the fix for this case will be issued.
