### ISSUE TITLE
Confusing .php.tools.ini

### ISSUE THREAD

**Issue by iwat** [phpfmt/php.tools#87]
What's different between?
- `visibility_order=1` and `pass=PSR2ModifierVisibilityStaticOrder,...`
- `smart_linebreak_after_curly=1` and `pass=SmartLnAfterCurlyOpen,...`
- `yoda=1` and `pass=YodaComparisons,...`

I believe that CLI options are made available for backward compatibility, but does it necessary for default `.php.tools.ini`

**Comment by ccirello** [comment]
They exist just for backward compatibility. No need for them anywhere.
