### ISSUE TITLE
if, elseif, else on separate lines

### ISSUE THREAD

**Issue by fabriziogiordano** [phpfmt/php.tools#90]
I am new here so I apologize for the dumb question.

Is it possible to have else on a new line;

### From
```php
if (...) {
//body
} else if(...) {
//body
}
```

### To
```php
if (...) {
    //body
}
elseif (...) {
    //body
}
```

Also if there if there is a comment before the `if` not add an extra line when `SpaceAroundControlStructures` is set.

### From
```php
//comment that explain the if
if (...) {
    //body
}
$someothercode...
```

### To
```php
//comment that explain the if
if (...) {
    //body
}

$someothercode...
```

**Comment by ccirello** [comment]
Please open separated requests in separated GH issues. 

I am do not rule out the first request, but I don't see it in any standard. Is it a personal style? If it's a personal style, then I recommend you to use fmt-external with a customized pass you yourself would write for php.tools. 

Re: the spaces, it seems a bug to me. Please make it sure it shows up in a different GH issue.

**Comment by fabriziogiordano** [comment]
Thank you. Is there a wiki or some guide to follow for edit fmt-external ?

**Comment by ccirello** [comment]
Not yet! But it is on the works. Right now, all you need to do is make a class extending `SandboxedPass`
