### ISSUE TITLE
Configuration file sample

### ISSUE THREAD

**Issue by JanisE** [phpfmt/php.tools#94]
A configuration file sample would be nice. I found (by way of reading source code comments) that it may be either JSON or a PHP file that returns an array, but what is the format?

Especially this option needs samples:
> `--profile=NAME` use one of profiles present in configuration file

I could guess a simple format like `['lint-before' => true, 'indent_with_spaces' => 8]`, but how to define profiles?!

**Comment by ccirello** [comment]
You are completely wrong. It is an ini file. JSON or something that returns an array, you are probably thinking of php-cs-fixer. Take a look at src/.php.tools.ini for a valid example with profiles.

**Comment by JanisE** [comment]
Yes, thank you for the example!
