### ISSUE TITLE
RemoveIncludeParentheses produces doublespaces

### ISSUE THREAD

**Issue by JanisE** [phpfmt/php.tools#95]
`require_once "$includes_path/io_functions.php";	// GetIOOnIntervals`
gets formatted to
`require_once  "$includes_path/io_functions.php";	// GetIOOnIntervals`
by "RemoveIncludeParentheses" pass.

The difference is the added space (gets removed by GitHub markup, even if formatted as code) after `require_once`, which should not be there, in my opinion.

**Comment by ccirello** [comment]
You can disable this pass should you feel this is not good for you. Use the exclude option.
