### ISSUE TITLE
--help-pass=ReindentEqual not working

### ISSUE THREAD

**Issue by JanisE** [phpfmt/php.tools#96]
$ php fmt.phar --help-pass=ReindentEqual
fmt.phar: "ReindentEqual" - PHP Fatal error:  Call to undefined method ReindentEqual::getDescription() in phar:///home/janis/bin/phpfmt/php.tools/fmt.phar/fmt.stub.php on line 12633

The same for "ReindentObjOps" (on line 2633) and "NormalizeIsNotEquals" (on line 12633).

**Comment by ccirello** [comment]
Uhm core passes don't have documentation. I should treat these case differently. It's a bug. I'm going to fix it asap.
