### ISSUE TITLE
AddMissingCurlyBraces loses the indent completely

### ISSUE THREAD

**Issue by JanisE** [phpfmt/php.tools#97]
Original code:
```
<?php

if (true) {
	if (true) {
		if (true) {
			print 1;
		}
		else foreach ([1, 2] as $i) {
			print 0;
		}
	}
}
```

Formatted code:
```
<?php

if (true) {
	if (true) {
		if (true) {
			print 1;
		}
		else {
foreach ([1, 2] as $i) {
			print 0;
		}
}

	}
}
```

Expected formatted code:
```
<?php

if (true) {
	if (true) {
		if (true) {
			print 1;
		}
		else {
			foreach ([1, 2] as $i) {
				print 0;
			}
		}

	}
}
```
or at least
```
<?php

if (true) {
	if (true) {
		if (true) {
			print 1;
		}
		else {
		foreach ([1, 2] as $i) {
			print 0;
		}
		}

	}
}
```

Code formatted by:
`php fmt.phar --passes=AddMissingCurlyBraces,LeftAlignComment,ReindentEqual,RTrim,ShortArray --exclude=EliminateDuplicatedEmptyLines,ExtraCommaInArray,Reindent,ReindentObjOps,ReindentColonBlocks,SplitCurlyCloseAndTokens,ResizeSpaces,StripExtraCommaInList,MergeDoubleArrowAndArray,MergeCurlyCloseAndDoWhile,MergeParenCloseWithCurlyOpen,NormalizeLnAndLtrimLines,OrderAndRemoveUseClauses,NormalizeIsNotEquals,RemoveIncludeParentheses,TwoCommandsInSameLine -o=test_formatted.php test.php```

**Comment by ccirello** [comment]
Unlike php-cs-fixer, php.tools passes are not atomic. They are supposed to be used with each other. 

It means Core passes must always be used together, and their behavior be overridden through additional passes. 

It works as intended, in the sense that if you exclude almost all core passes, then you're going to have an incomplete pretty printer.

**Comment by JanisE** [comment]
OK, thanks, I'll take a look at php-cs-fixer. I really want to pick which specific rules are applied and which are not (as we do not want to enforce too many preferences to our developers).

**Comment by ccirello** [comment]
Good luck :)
