### ISSUE TITLE
How to use the refactor tool in sublime text.

### ISSUE THREAD

**Issue by chris-schmitz** [phpfmt/php.tools#98]
This is a question about the sublime text version of the tool (which asks that issues be opened in this project). 

Are there instructions on how to use the refactor tool? I started reading through the code to try to figure out how to use it but I got a bit lost. 

Are there instructions posted somewhere on the intended use of the tool that I could refer to?

Thanks.

**Comment by ccirello** [comment]
Command palette, `phpfmt: refactor`

First you type some piece of PHP code which needs to be search for. Hit enter.
Second you type what is to be replaced with once the initial piece of code is found. Hit enter.

It will search and replace your code taking in consideration the context. I haven't release the more advanced features that allows more advanced constructs. But you should be able to change function calls, method calls, variable names and etc with the refactor call.

I might disable it in the future releases should it fail to work with PHP 7.0.

**Comment by chris-schmitz** [comment]
Gotcha. Thanks for the explanation and the head's up re: php 7.
